# Generated by Django 4.1 on 2022-09-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="name", new_name="book_name",
        ),
    ]
